version: '3.7'
# version: "2.4"

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - app-tier

    mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        volumes:
            - mongodbdata:/data/db
        networks:
            - app-tier

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn -w 1 -b 0.0.0.0:5000 server:app --reload
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
        links:
            - mongodb:mongodb   
        depends_on: 
            - mongodb
        networks:
            - app-tier
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - client
            - api
        networks:
            - app-tier
        restart: "on-failure"   
networks:
    app-tier:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
